### ISSUE TITLE
SELECT in compound selects or LIMIT clauses can't resolve CTE

### ISSUE THREAD

**Issue by LeMikaelF** [tursodatabase/turso#3952]
In compound selects:

Turso

```
turso> with t as (select * from (values(2))) values(1) union all select * from t;
  × Parse error: no such table: t
```

SQLite:

```
sqlite> with t as (select * from (values(2))) values(1) union all select * from t;
1
2
```

---

In LIMIT clauses:

Turso:

```
turso> with t as (select 1) select 1 limit (select * from t);
  × Parse error: no such table: t
```

SQLite:

```
sqlite>  with t as (select 1) select 1 limit (select * from t);
1
```

**Comment by LeMikaelF** [comment]
fixed now

**Comment by RyanLin5967** [comment]
The LIMIT half of this is still failing on main, though the compound-arm half is fixed.

```sql
WITH t AS (SELECT * FROM (VALUES(2))) VALUES(1) UNION ALL SELECT * FROM t;
-- both 1,2, so the compound arm case is fixed

WITH t AS (SELECT 1) SELECT 1 LIMIT (SELECT * FROM t);
-- Turso:  Parse error: no such table: t
-- SQLite: 1
-- the CTE still isn't visible from inside the LIMIT subquery
```

tested on main & SQLite 3.50.4

**Comment by LeMikaelF** [comment]
@RyanLin5967 thanks, I've created https://github.com/tursodatabase/turso/issues/8569
